### ISSUE TITLE
Dateparsing for Month does not work

### ISSUE THREAD

**Issue by Freshwood** [Archakov06/jQuery.tableExport#3]
Hi guys,

this tool is really nice when you want to export stuff quick and easy.

Thank you for your work!!!!

Anyway I found a little problem on the date parsing feature for the filename.

It seems that parsing the month with **%MM%** does not seems to work.

Example code:

`    function exportTable(type) {
        $('#alarmTable').tableExport({
                                    filename: 'alarm_export_%DD%-%MM%-%YY%_%hh%:%mm%:%ss%',
                                    format: type
                                });
    }`

I tested this with the Chrome browser.

Best wishes and greetz,

Freshwood

**Comment by Archakov06** [comment]
Hello, @Freshwood. Thank you for that use my plugin and found a bug. It's nice for such a good review. I will fix it in the near future :)

**Comment by Archakov06** [comment]
@Freshwood fixed. Check now

**Comment by Freshwood** [comment]
Nope was not really ok.
I added a pull request with the fix ;)
Greetz Freshwood

**Comment by Archakov06** [comment]
@Freshwood Oh, yeah! :) Thank you, I have not noticed that MM: used method getDate(). Thank you for pull request!

**Comment by Freshwood** [comment]
No problem man :)
